<?php
/**
 * Copyright © magebig.com - All rights reserved.
 * See LICENSE.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
$_product = $block->getProduct();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$productUrl = $_helper->productAttribute($_product, $_product->getProductUrl(), 'product_url');
$productName = $_helper->productAttribute($_product, $_product->getName(), 'name');
?>
<div class="social-share">
    <ul class="social-listing">
        <li class="facebook">
            <button type="button" class="share-item mb-tooltip" title="<?= __('Share on Facebook') ?>" onclick="window.open('https://www.facebook.com/sharer/sharer.php?u='+'<?= $productUrl ?>');return false;"><span class="mbi mbi-facebook"></span></button>
        </li>
        <li class="twitter">
            <button type="button" class="share-item mb-tooltip" title="<?= __('Share on Twitter') ?>" onclick="window.open('https://twitter.com/share?text=<?= $productName ?>&amp;url=<?= $productUrl ?>');return false;"><span class="mbi mbi-twitter"></span></button>
        </li>
        <li class="email">
            <button type="button" class="share-item mb-tooltip" title="<?= __('Share via Gmail') ?>" onclick="window.open('https://mail.google.com/mail/u/0/?view=cm&amp;fs=1&amp;to&amp;su=<?= $productName ?>&amp;body=<?= $productUrl ?>&amp;ui=2&amp;tf=1');return false;"><span class="mbi mbi-google"></span>
            </button>
        </li>
    </ul>
</div>