<?php
$qvHelper = $this->helper('Magekc\QuickView\Helper\Data');
$itemClass = $block->escapeHtmlAttr($qvHelper->getConfig('quickview/general/item_class'));
$target = $block->escapeHtmlAttr($qvHelper->getConfig('quickview/general/target'));
$autoAddButtons = $qvHelper->getConfig('quickview/general/auto_add_buttons');
?>

<div class="quickview-popup" style="display:none">
</div>
<!-- Init component via data-mage-init attribute -->
<script type="text/x-magento-init">
{
	"*":{
		"Magekc_QuickView/js/quick-view": {
            "options": {
				"baseUrl": "<?= $qvHelper->getBaseUrl() ?>",
				"quickviewLabel": "<i class='mbi mbi-eye'></i>",
				"itemClass": "<?= (!empty($itemClass))?$itemClass:"" ?>",
				"target": "<?= (!empty($target))?$target:".product-item-info"; ?>",
				"autoAddButtons":<?= ($autoAddButtons==1)?"true":"false" ?>
			}
        }
	}
}
</script>
